### PR TITLE
Private events

### PR DESCRIPTION
**Pull request by rayking12**
things to look at for :
- Ability to create a user
- ability to create events
- able to invite other users
- ablility to accept invitations

### CODE REVIEW

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @rayking12  & @Oxford-G**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] user show page should also display past events attended by the user.
- [ ] when i try to manually navigate to a user's show page e.g. http://127.0.0.1:3000/users/1  while not logged in it throws an error. please make sure to fix that.
- [ ] you should have better error handling, meaning that if i try to access a non-existing user's show page it throws an error. what should happen is that if you can't find a user with his id you should redirect him to the home page with  flash error massage. make sure to apply the required logic for this to happen. and you should do this with all the other actions.

- [ ] using Time.zone.now in your scopes is better as it compares global time in case that your website is a used by user's all over the world. 



---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Gerald Enekwechi & King Ray** 
Nice job with your first submission for this project :muscle:  :muscle:
The authentication and create event are working properly :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [ ] Add unit tests
- [ ] Add integration tests for authentication and event management
- [ ] Remove commented code in user_controller.rb
- [ ] User should have the option to attend an event, even its own events
- [ ] In users show, use the scopes you created for previous and upcoming events
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by Oxford-G** [comment]
Hi Andres,
I don't understand what you mean by unit tests and integration tests.
I already have a way for inviting users (by clicking on the created event by the user) which will send an invitation request to the invitee

**Review by enaburekhan — APPROVED** [review]
# Status: Project Approved:heavy_check_mark:
Hi team!
Nice job on implementing all the required changes:clap::clap:. The UI is awesome:blush:.
Move on with the next task:walking:.

Kindly drop your questions :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Have a great day:blush:
Eric Enaburehan.

**Pull request merged**
